---
title: "Exam - Reinforcement Learning for Business"
author: "Lars Relund Nielsen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Practicalities

- Be ready in front of the exam room on time.
- Bring your project report as hard copy or easy available on your computer.
- Remember to bring your student id card.
- We will have pen and paper, or you may use the blackboard. 
- You are not allowed to look in your notes during the exam.


## Format

The exam is a 20 min oral individual exam without any preparation. Since we nee time for giving you the correct grade, this means that:

- The oral examination lasts 15 minutes exactly.
- You might be interrupted in the middle of a sentence which is not to be rude but to make sure we stick to the schedule.
- The exam will begin by you picking one of the exam-topics specified. For each topic prepare a 4-6 minutes pitch where you explain the core concepts and what you find important and relevant.
- We will use the last minutes to ask questions, e.g. about the example in your project report or link your pitch to other topics in the curriculum.

## Exam-topics

The following topics can be selected:

1) Multi-armed bandits
2) Markov decision processes (MDPs)
3) Policies and value functions for MDPs
4) Dynamic programming
5) Monte Carlo methods for prediction and control
6) Temporal difference methods for prediction
7) Temporal difference methods for control

Have a look at the learning goals for each topic to get an overview over the topic.
